package com.example.recyclerview

data class Names(var name: String)

object Supplier {
    val names = listOf(
        Names("A"),
        Names("s"),
        Names("d"),
        Names("f"),
        Names("g"),
        Names("h"),
        Names("j"),
        Names("k"),
        Names("l"),
        Names("q"),
        Names("w"),
        Names("e"),
        Names("r"),
        Names("t"),
        Names("y"),
        Names("y"),
        Names("yA"),
        Names("u"),
        Names("i"),
        Names("o"),
        Names("p"),
        Names("Ab"),
        Names("Ac"),
        Names("Ax"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("A"),
        Names("k"),
        Names("l"),
        Names("q"),
        Names("w"),
        Names("e"),
        Names("r"),
        Names("t"),
        Names("y"),
        Names("y"),
        Names("yA"),
        Names("u"),
        Names("i"),
        Names("o"),
        Names("p"),
        Names("Ab"),
        Names("Ac"),
        Names("Ax"),
        Names("A")
        )
}